RF24Gateway - TCP/IP over RF24Network: RF24Gateway Class Reference
RF24Gateway Class Reference
#include <RF24Gateway.h>
Classes
struct routeStruct
Public Member Functions
RF24Gateway (RPi/Linux)
RF24Gateway library for devices with an IP stack
RF24Gateway (RF24 &_radio, RF24Network &_network, RF24Mesh &_mesh)
void begin (uint8_t nodeID=0, uint8_t channel=97, rf24_datarate_e data_rate=RF24_1MBPS)
void begin (uint16_t address, uint8_t channel=97, rf24_datarate_e data_rate=RF24_1MBPS, bool meshEnable=0, uint8_t nodeID=0)
int setIP (char *ip_addr, char *mask)
void update (bool interrupts=0)
void poll (uint32_t waitDelay=3)
void interrupts (bool enable=1)
Advanced Operation
More advanced methods and options
uint16_t thisNodeAddress
uint8_t thisNodeID
bool config_TUN
bool fifoCleared
bool meshEnabled ()
uint32_t ifDropped ()
void sendUDP (uint8_t nodeID, RF24NetworkFrame frame)
Routing Table
Utilizing a routing table to provide complete connectivity
routeStruct routingStruct [256]
uint8_t routingTableSize
Detailed Description
Examples
RF24GatewayNode.cpp, RF24GatewayNodeInt.cpp, RF24Gateway_ncurses.cpp, and RF24Gateway_ncursesInt.cpp.
Definition at line 46 of file RF24Gateway.h.
Constructor & Destructor Documentation
RF24Gateway()
RF24Gateway::RF24Gateway (RF24 & _radio, RF24Network & _network, RF24Mesh & _mesh)
RF24Gateway constructor.
Definition at line 12 of file RF24Gateway.cpp.
Member Function Documentation
begin() [1/2]
void RF24Gateway::begin (uint8_t nodeID = 0, uint8_t channel = 97, rf24_datarate_e data_rate = RF24_1MBPS)
Begin function for use with RF24Mesh (TUN interface)
Parameters
nodeID The RF24Mesh nodeID to use
channel The radio channel to use (1-127)
data_rate The RF24 datarate to use (RF24_250KBPS, RF24_1MBPS, RF24_2MBPS)
gw.begin(); //Start the gateway using RF24Mesh, with nodeID 0 (Master)
uint8_t nodeID; gw.begin(nodeID); //Start the gateway using RF24Mesh, with nodeID 1 (Child node)
Definition at line 19 of file RF24Gateway.cpp.
References begin().
Referenced by begin().
begin() [2/2]
void RF24Gateway::begin (uint16_t address, uint8_t channel = 97, rf24_datarate_e data_rate = RF24_1MBPS, bool meshEnable = 0, uint8_t nodeID = 0)
Begin function for use with a TAP (Ethernet) interface. RF24Mesh can be used for address assignment, but ARP will be used to perform the lookups.
Parameters
address The RF24Network address to use
channel The radio channel (0-127) to use
data_rate The RF24 datarate to use (RF24_250KBPS, RF24_1MBPS, RF24_2MBPS)
meshEnable Whether to use RF24Mesh for address assignment
nodeID The RF24Mesh nodeID to use if meshEnable has been set to true
uint16_t address=00; gw.begin(address); //Start the gateway without using RF24Mesh, with RF24Network address 00 (Master)
uint16_t address=01; gw.begin(address); //Start the gateway without using RF24Mesh, with RF24Network address 01 (Child)
Definition at line 27 of file RF24Gateway.cpp.
References begin().
setIP()
int RF24Gateway::setIP (char * ip_addr, char * mask)
Once the Gateway has been started via begin() , call setIP to configure the IP and subnet mask.
Parameters
ip_addr A character array containing the numeric IP address ie: 192.168.1.1
mask A character array containing the subnet mask ie: 255.255.255.0
Returns
-1 if failed, 0 on success
Definition at line 243 of file RF24Gateway.cpp.
update()
void RF24Gateway::update (bool interrupts = 0)
Calling update() keeps the network and mesh layers active and processing data. This needs to be called regularly.
gw.update();
if(network.available()){
 ...do something
}
Parameters
interrupts Set true if called from an interrupt handler & call poll() from the main loop or a thread.
Definition at line 310 of file RF24Gateway.cpp.
References interrupts().
poll()
void RF24Gateway::poll (uint32_t waitDelay = 3)
gw.poll(); needs to be called to handle incoming data from the network interface. The function will perform a delayed wait of max 3ms unless otherwise specified.
Parameters
waitDelay How long in milliseconds this function will wait for incoming data.
Definition at line 326 of file RF24Gateway.cpp.
References fifoCleared.
interrupts()
void RF24Gateway::interrupts (bool enable = 1)
When using interrupts (gwNodeInt, ncursesInt examples) users need to call this function to disable interrupts before accessing the radio and again to re-enable interrupts when complete
Parameters
enable 0 to disable interrupts and access the radio, 1 to re-enable
Definition at line 303 of file RF24Gateway.cpp.
Referenced by update().
meshEnabled()
bool RF24Gateway::meshEnabled ()
Is RF24Mesh enabled?
Definition at line 147 of file RF24Gateway.cpp.
ifDropped()
uint32_t RF24Gateway::ifDropped () inline
Definition at line 141 of file RF24Gateway.h.
sendUDP()
void RF24Gateway::sendUDP (uint8_t nodeID, RF24NetworkFrame frame)
Definition at line 696 of file RF24Gateway.cpp.
Member Data Documentation
thisNodeAddress
uint16_t RF24Gateway::thisNodeAddress
Address of our node in Octal format (01,021, etc)
Definition at line 134 of file RF24Gateway.h.
thisNodeID
uint8_t RF24Gateway::thisNodeID
NodeID (0-255)
Definition at line 135 of file RF24Gateway.h.
config_TUN
bool RF24Gateway::config_TUN
Using a TAP(false) or TUN(true) interface
Definition at line 138 of file RF24Gateway.h.
fifoCleared
bool RF24Gateway::fifoCleared
Definition at line 139 of file RF24Gateway.h.
Referenced by poll().
routingStruct
routeStruct RF24Gateway::routingStruct[256]
The array that holds the routing structure data. See routeStruct
Definition at line 194 of file RF24Gateway.h.
routingTableSize
uint8_t RF24Gateway::routingTableSize
The size of the existing routing table loaded into memory. See routeStruct
Definition at line 199 of file RF24Gateway.h.