name: build Docs

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "*.h"
      - "*.md"
      - "docs/**"
      - "!**README.md"
      - "examples**.cpp"
      - ".github/workflows/doxygen.yml"
      - "Doxyfile"
  push:
    paths:
      - "*.h"
      - "*.md"
      - "docs/**"
      - "!**README.md"
      - "examples**.cpp"
      - ".github/workflows/doxygen.yml"
      - "Doxyfile"
  release:
    branches: [master]
    types: [published, edited]
  workflow_dispatch:

jobs:
  build-docs:
    uses: nRF24/.github/.github/workflows/build_docs.yaml@main
    with:
      deploy-gh-pages: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master') }}
    secrets: inherit
